### ISSUE TITLE
Image resize on dynamically added images

### ISSUE THREAD

**Issue by sandeepmane748** [davidjbradshaw/image-map-resizer#24]
how can we use image resizer when image is hidden on initial page load and its coming on some user event

**Comment by davidjbradshaw** [comment]
Call the setup script, the first time the user event happens.

**Comment by sandeepmane748** [comment]
Thanks David , but is there any way were we can set up on hidden images ?

**Comment by davidjbradshaw** [comment]
The issue is that when you show the image you're resizing it. The image doesn't have a resize event handler that can be used to detect this. Try the dev version which will support you calling the setup every time you unhide the image.

https://github.com/davidjbradshaw/image-map-resizer/tree/dev

If you can find a suitable event handler, please fill free to submit a pull request,

**Comment by sandeepmane748** [comment]
Surely will try the dev version , currently I have achieved the same by
checking if image is present on page then I'm unhiding it and calling
imagemap resizer and then again hiding it which solved my issue. Thanks for
your advice.
