### ISSUE TITLE
Hidden image maps don't resize

### ISSUE THREAD

**Issue by Adyyda** [davidjbradshaw/image-map-resizer#26]
Hello. To demonstrate the issue please take a look at http://jsfiddle.net/Adyyda/f2726u7g/3/

If i place the map in tab 1, the map will be ok.
If i place it in tab 3, the map will stop working properly - all links are condensed in top left corner instead of proper position, over each state hover.

Any idea how to fix to this?

Olso, can you tell me how we can add a hover colour or border when we hover a state? Thanks

**Comment by davidjbradshaw** [comment]
Interesting bug. The issue is the image map needs to be visible on the page when you call the function. You can likely work around this by calling `$(window).trigger('resize'); after changing tab.

**Comment by Adyyda** [comment]
Hello. Thanks for the reply. Can you apply the change you mentioned in the jsfiddle that i provided? I do not know where to add it. Thanks

**Comment by davidjbradshaw** [comment]
After fadeIn() has finished running.

**Comment by Adyyda** [comment]
Unfortunately is not working http://jsfiddle.net/Adyyda/f2726u7g/4/

**Comment by davidjbradshaw** [comment]
You need to do it after fadeIn has finished running.

**Comment by Adyyda** [comment]
I have already placed your code after this line $(tab).fadeIn(); and is not working. Unless this is not what you are telling me to do - i am not good with jquery

**Comment by davidjbradshaw** [comment]
You need to put it in a callback function passed fadeIn. See jQuerry docs.

**Comment by AlyssaRobyn** [comment]
Hi David:

I have spent hours attempting to use your plugin with a jQuery Mobile app - it is successful and working on the initial page and none of the other pages (they are hidden until loaded with jQuery Mobile's pagecontainer's "change" function, so I believe it is related to this bug).

After finding this bug report and testing thoroughly, I tried your recommendation with `$(window).trigger('resize');` after the page change, it was unsuccessful. (the plugin still reported image.height and image.width as the fullsize imagemap and therefore `resizeMap()` didn't trigger)

Since you stated it was likely due to needing the imagemap displayed before `$('map').imageMapResize();`, I also attempted to use multiple native jQuery Mobile event listeners that hook AFTER the page/imagemap is displayed  (`pagecontainershow` and I also tried `pagecontainertransition`) to reload the imagemap with the plugin, and still no luck.

I no longer believe this is a jQuery Mobile issue, but rather something to do with the hidden imagemaps and plugin. 

Thank you for your time, and let me know if there is anything I can do to assist in debugging this!

Alyssa
